name = "SimpleLinearAlgebra"
uuid = "555e9691-8231-4cde-a0d7-6dc20204a59a"
authors = ["Junjie Yang <yangjunjie0320@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
