name = "SimpleLinearAlgebra"
uuid = "555e9691-8231-4cde-a0d7-6dc20204a59a"
authors = ["Junjie Yang <yangjunjie0320@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
